import type { Metadata } from "next";
import { ARTICLES } from "@/data/blog";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const article = ARTICLES.find((a) => a.slug === slug);

  if (!article) {
    return {
      title: "Статья не найдена — Блог Abadan & Co.",
    };
  }

  const url = `https://abadan.kz/blog/${article.slug}`;
  const ogImage = article.image.startsWith("/")
    ? `https://abadan.kz${article.image}`
    : article.image;

  return {
    title: `${article.title} — Блог Abadan & Co.`,
    description: article.excerpt,
    keywords: [
      article.category,
      "корпоративное обучение Казахстан",
      "HR Казахстан",
      "бизнес-тренинги",
      "Abadan & Co.",
      article.author,
    ],
    authors: [{ name: article.author }],
    openGraph: {
      title: article.title,
      description: article.excerpt,
      url,
      type: "article",
      publishedTime: article.date,
      authors: [article.author],
      // OG image auto-generated by opengraph-image.tsx (PNG, 1200x630)
    },
    twitter: {
      card: "summary_large_image",
      title: article.title,
      description: article.excerpt,
      // Twitter image auto-generated by opengraph-image.tsx
    },
    alternates: { canonical: url },
  };
}

export default async function ArticleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const article = ARTICLES.find((a) => a.slug === slug);

  if (!article) return <>{children}</>;

  const url = `https://abadan.kz/blog/${article.slug}`;
  const ogImage = article.image.startsWith("/")
    ? `https://abadan.kz${article.image}`
    : article.image;

  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: article.title,
    datePublished: article.date,
    dateModified: article.date,
    author: { "@type": "Person", name: article.author },
    publisher: {
      "@type": "Organization",
      name: "Abadan & Co.",
      logo: { "@type": "ImageObject", url: "https://abadan.kz/images/logo.png" },
    },
    image: ogImage,
    description: article.excerpt,
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
  };

  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Главная", item: "https://abadan.kz" },
      { "@type": "ListItem", position: 2, name: "Блог", item: "https://abadan.kz/blog" },
      { "@type": "ListItem", position: 3, name: article.title, item: url },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      {children}
    </>
  );
}
